list: $/wiz/blog/models/category/columns.yaml
modelClass: Wiz\Blog\Models\Category
title: Categorías
recordUrl: 'wiz/blog/categories/update/:id'
noRecordsMessage: 'Aun no se ingresan categorías en el sistema'
recordsPerPage: 10
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'Buscar...'
showSorting: 1
defaultSort: published_at desc
showCheckboxes: 1
showSetup: 1