title: 'Contenido Multimedia'
modelClass: Wiz\Blog\Models\Asset
list: $/wiz/blog/models/asset/columns.yaml
recordUrl: 'wiz/blog/multimedia/preview/:id'
noRecordsMessage: 'Aún no se cargan contenidos multimedia en el sistema'
recordsPerPage: '10'
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: created_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
